#!/usr/bin/env python3
"""Commit message validation (policy + format).

Enforces two CONTRIBUTING.md rules that previous review waves measured as
violated in 5 consecutive commits:

1. Prohibited phrases (existing rule): no commit message may claim
   deployment/production readiness — only the QA gate may declare that.

2. Conventional Commit format (new, F8-L-06-R2): the first line must be
   ``<type>(<optional scope>)!: <subject>`` with type in
   {feat, fix, docs, style, refactor, perf, test, chore, build, ci}.
   The maintainability review (2026-09) documented status-essay subjects
   (``Update: ...``) displacing change descriptions as an eroding
   pattern; this gate makes the format machine-checkable so the pattern
   cannot recur silently. The 50-character subject guidance stays a
   documented convention, deliberately not enforced: history shows long
   evidence-carrying subjects are the norm here, and the gate's job is
   structure, not prose policing.

Merge and revert commits are exempt from the format rule (their first
line is generated by git) but never from the prohibited-phrase rule.

Usage (pre-commit commit-msg hook / manual):
    python scripts/commit_message_check.py <path-to-commit-msg-file>

Exit codes: 0 = valid; 1 = violation (printed).
"""

from __future__ import annotations

import re
import sys

# Case-insensitive substrings that must never appear in a commit message
# (CONTRIBUTING.md "Prohibited Phrases").
PROHIBITED_PHRASES: tuple[str, ...] = (
    "ready for deployment",
    "production ready",
    "ready for production",
    "deployment ready",
    "production-ready",
    "deployment-ready",
)

# Conventional Commit types accepted as live change descriptions.
CONVENTIONAL_TYPES: frozenset[str] = frozenset(
    {"feat", "fix", "docs", "style", "refactor", "perf", "test", "chore", "build", "ci"}
)

_SUBJECT_RE = re.compile(
    r"^(?P<type>[a-z]+)(\((?P<scope>[^()]+)\))?(?P<bang>!)?: (?P<subject>\S.*)$"
)

# First lines generated by git itself; format rule does not apply.
_EXEMPT_PREFIXES = ("merge ", "revert ", "fixup!", "squash!")


def _format_violation(first_line: str) -> str | None:
    """Return a reason string if ``first_line`` violates the format rule."""
    if first_line.lower().startswith(_EXEMPT_PREFIXES):
        return None
    match = _SUBJECT_RE.match(first_line)
    if match is None:
        return (
            f"first line {first_line!r} is not '<type>(<scope>)!: <subject>' "
            f"with type in {sorted(CONVENTIONAL_TYPES)}"
        )
    if match.group("type") not in CONVENTIONAL_TYPES:
        return (
            f"commit type {match.group('type')!r} is not one of "
            f"{sorted(CONVENTIONAL_TYPES)}"
        )
    return None


def main() -> int:
    if len(sys.argv) < 2:
        print("ERROR: No commit message file provided")
        return 1
    commit_msg_file = sys.argv[1]
    try:
        with open(commit_msg_file, encoding="utf-8") as f:
            commit_message = f.read()
    except FileNotFoundError:
        print(f"ERROR: Commit message file not found: {commit_msg_file}")
        return 1
    except OSError as exc:
        print(f"ERROR reading commit message file: {exc}")
        return 1

    # Rule 1: prohibited phrases (case-insensitive, whole message).
    lowered = commit_message.lower()
    found = [p for p in PROHIBITED_PHRASES if p in lowered]
    if found:
        print("ERROR COMMIT REJECTED: Commit message contains prohibited phrases:")
        for phrase in found:
            print(f"  - '{phrase}'")
        print()
        print("CONTRIBUTING.md prohibits claiming deployment readiness;")
        print("only the QA gate may declare production readiness.")
        return 1

    # Rule 2: Conventional Commit first line (F8-L-06-R2).
    first_line = (
        commit_message.strip().splitlines()[0].strip() if commit_message.strip() else ""
    )
    reason = _format_violation(first_line)
    if reason is not None:
        print("ERROR COMMIT REJECTED: Commit message violates the required format.")
        print(f"  {reason}")
        print()
        print("Required (CONTRIBUTING.md): <type>(<optional scope>)!: <subject>")
        print(f"Types: {', '.join(sorted(CONVENTIONAL_TYPES))}")
        print(
            "Merge/revert commits are exempt. Status-essay subjects "
            "(e.g. 'Update: ...') are not change descriptions; put wave "
            "evidence in reports/ and docs/audit-history/ instead."
        )
        return 1

    print("OK Commit message validation passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
